# Netlify Configuration for Geriatrics Fellowship Platform

[build]
  publish = "."
  
# Plugin Configuration (if plugins installed via UI)

# Lighthouse CI Configuration
[build.environment]
  LIGHTHOUSE_PRESET = "desktop"
  
# Build settings
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    # Test these critical pages
    audits = [
      { "path": "/" },
      { "path": "/patient-dashboard.html" },
      { "path": "/drug-interaction-checker.html" },
      { "path": "/comprehensive-tools.html" }
    ]
    
    # Performance thresholds (0-1 scale)
    [plugins.inputs.thresholds]
      performance = 0.8
      accessibility = 0.9
      best-practices = 0.8
      seo = 0.8
      pwa = 0.6

# Sitemap Plugin Configuration  
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    buildDir = "."
    exclude = [
      "./offline.html",
      "./404.html"
    ]
    
# Checklinks Plugin Configuration
[[plugins]]
  package = "netlify-plugin-checklinks"
  
  [plugins.inputs]
    entryPoints = [
      "index.html",
      "patient-dashboard.html",
      "drug-interaction-checker.html"
    ]
    recursive = true
    pretty = true
    skipPatterns = [
      "mailto:",
      "tel:",
      "#"
    ]

# Headers Configuration for Security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for Common Medical Terms
[[redirects]]
  from = "/drugs"
  to = "/drug-interaction-checker.html"
  status = 301

[[redirects]]
  from = "/calculators"
  to = "/comprehensive-tools.html"
  status = 301

[[redirects]]
  from = "/emergency"
  to = "/oncall-copilot.html"
  status = 301

[[redirects]]
  from = "/rounds"
  to = "/patient-dashboard.html"
  status = 301

[[redirects]]
  from = "/interactions"
  to = "/drug-interaction-checker.html"
  status = 301

[[redirects]]
  from = "/tools"
  to = "/comprehensive-tools.html"
  status = 301

# 404 handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Environment Variables
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"